default: &default
  host: localhost
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  timeout: 5000
  database: seans_test_app
  username: seans_test_app
  password: s3ans_t3st_app
  ssl: false

development:
  <<: *default

test:
  <<: *default
